#!/bin/bash

if [ "$1" == "nuke" ]; then

  echo ""
  echo ""
  echo "     _.-^^---....,,--        "
  echo " _--                  --_    "
  echo " <                        >) "
  echo " |                         | "
  echo "  \._                   _./  "
  echo "     '''--. . , ; .--'''     "
  echo "          | |   |            "
  echo "       .-=||  | |=-.         "
  echo "        -=#$%&%$#=-'         "
  echo "          | ;  :|            "
  echo "      .,-#%&$@%#&#~,         "
  echo "  -------------------------  "
  echo "  NUKING YOUR SAITO INSTALL  "
  echo "  -------------------------  "
  echo "  (resetting configuration)  "
  echo ""
  echo ""

  rm -f data/database.sq3
  rm -f data/bank.sq3
  rm -f data/registry.sq3
  rm -f data/log.txt
  rm -f data/*.sq3-journal
  rm -f data/blocks/*.blk
  rm -f data/blocks/*.zip
  rm -f data/blocks/*.segadd
  rm -f data/tmp/*.blk
  rm -f data/tmp/*.zip
  rm -f options
  rm -f modules/mod/registry/web/addresses.txt
  rm -f logs/*


#  cp -rfp data/fork1/* data/blocks/
  cp options.conf options

fi

  rm -f remixtmp.js
  rm -f saito/web/options
  rm -f saito/web/browser.js.gz
  rm -f saito/web/browser.js-*



# generate browser.js
sed 's/app.BROWSER    = 0;/app.BROWSER    = 1;/g' start.js > browser.js
./../node_modules/.bin/browserify browser.js -o saito/web/browser.js -i express -i sqlite3 -i express-basic-auth -i sendgrid -i request -i bluebird -i socket.io -i phantomjs -i express-fileupload -i body-parser -i shashmap -i http -i http-proxy -i simple-socks -i unzip -i node-zip -i shelljs -i crx -i jimp -i image-resolver -i fs-extra -i fs 

#-i winston -i winston-daily-rotate-file
rm browser.js






if [ "$1" == "nuke" ]; then

  for d in modules/mods/* ; do
   if [ -f $d/compile ] ; then
     chmod +x $d/compile
     $d/compile
   fi
  done

elsif

  for d in modules/mods/* ; do
   if [ -f $d/refresh ] ; then
     chmod +x $d/refresh
     $d/refresh
   fi
  done

fi




echo ""
echo "///////////////"
echo "// IMPORTANT //"
echo "///////////////"
echo "Saito will default to running on a local, private network for "
echo "development and testing unless you create a configuration file"
echo "specifying a connection point to the public network.          "
echo ""
echo "You can start Saito by running: "
echo ""
echo "$> node start.js "
echo ""
echo ""


